### ISSUE TITLE
css世界阅读笔记

### ISSUE THREAD

**Issue by pavelShen** [pavelShen/blog2#1]
#### 需求:页面某个模块的文字内容是动态的，可能是几个字，也可能是一句话。然后，希望文字少的时候居中显示，文字超过一行的时候居左显示

```css
.box {
      text-align: center;
}
.content {
      display: inline-block;
      text-align: left;
}
```

#### 需求：原生普通文本框&lt;input&gt;和文本域&lt;textarea&gt;的 100%自适应父容器宽度

书中推荐增加标签，宽度分离的样式书写方式来实现box-sizing的效果，个人持保留意见
而该需求无法通过上述方法来实现，只有通过设置box-sizing
替换元素的特性之一就是尺寸由内部元素决定，且无论其 display 属性值是 inline 还是 block,
&lt;textarea&gt;是有 border 的，而且需要有一定的 padding 大小，否则输入的时候光标会顶着边框，体验很不好
所以不能通过重置替换元素的margin和padding来处理

```css
.demo2-box{
      background: #452a5a;
      margin-bottom:20px;
      width:400px;
}
.demo2-box textarea{
      width:100%;
      height:100%;
      display:block;
}
.demo2-box-2 textarea{
      box-sizing: border-box
}
```

```html
<div class="demo2-box demo2-box-1">
  <textarea name="" id="" cols="30" rows="10"></textarea>
</div>
<div class="demo2-box demo2-box-2">
  <textarea name="" id="" cols="30" rows="10"></textarea>
</div>
```

#### 高度100%失效问题
```css
/* 方案1 */
html, body {
      height: 100%;
}
/* 方案2 */
 div {
      height: 100%;
      position: absolute;
}
```

#### min-height/min-width/max-height/max-width初始值

max-height/max-width的初始值为none
min-width/min-height 的初始值都是 auto,所以
```css
.box {
    transition: min-height .3s;
    background:bisque;
}
.box:hover {
    min-height: 300px;
}

box2 {
      min-height:0;
      transition: min-height .3s;
      background:bisque;
}
.box2:hover {
      min-height: 300px;
}
```
box没有过渡效果而box2有过渡效果

#### 任意高度元素的展开收起动画

因为高度是不固定的，height 使用的值是默认的 auto， 而 auto 是个关键字值，并非数值，正如 height:100%的 100%无法和 auto 相计算一样，从 0px 到 auto 也是无法计算的，因此无法形成过渡或动画效果。

```css
/* 失败的例子 */
.element {
      height: 0;
      overflow: hidden;
      transition: height .25s;
}
.element.active {
  height: auto; /*没有transition效果，只是生硬地展开*/ 
}

/* 成功的例子 */
.element {
      max-height: 0;
      overflow: hidden;
      transition: max-height .25s;
}
.element.active {
    max-height: 666px; /* 一个足够大的最大高度值 */ 
}
```

#### 需求：增加按钮的点击区域，不改变布局

方案：内联元素设置padding

#### 需求：a标签锚点跳转位置偏移（可能情况：有fixed的导航元素，标题太靠顶部）

方案：内联元素设置padding

```html
<style>
h3 {
       line-height: 30px;
       font-size: 14px;
       overflow:hidden;
}
h3 > span {
       padding-top: 58px;
}
</style>
<h3><span id="hash">标题</span></h3>
```

#### 等比例矩形（16：9的视频）
纵向padding的百分比根据宽度进行计算
```css
.video-box{
      position: relative;
      width:100%;
      height:0;
      padding-top:56.25%;
}
.head-video{
      width:100%;
      height:100%;
      position: absolute;
      left:0;
      top:0;
 }
```

#### button语义行为模拟
小程序中一些强制button行为 很好的处理方案
```html
<style>
button {
      position: absolute;
      clip: rect(0 0 0 0);
}
label {
      display: inline-block;
      line-height: 20px;
      padding: 10px;
}
</style>
<button id="btn"></button> <label for="btn">按钮</label>
```

##### 父元素和外部合并
对于 margin-top 合并，可以进行如下操作(满足一个条件即可):
- 父元素设置为块状格式化上下文元素;
- 父元素设置 border-top 值;
- 父元素设置 padding-top 值;
- 父元素和第一个子元素之间添加内联元素进行分隔。

对于 margin-bottom 合并，可以进行如下操作(满足一个条件即可):
- 父元素设置为块状格式化上下文元素;
- 父元素设置 border-bottom 值;
- 父元素设置 padding-bottom 值;
- 父元素和最后一个子元素之间添加内联元素进行分隔;
- 父元素设置 height、min-height 或 max-height。

#### 水平垂直居中
```css
.son {
       position: absolute;
       top: 0; right: 0; bottom: 0; left: 0;
       width: 200px; height: 100px;
       margin: auto;
}
```

#### margin失效情况
- display:inline 非替换元素的垂直margin
- display:table-cell或table-row
- 绝对定位元素非定位方向的margin
- 定高容器子元素的margin-bottom
- display:inline 替换元素的垂直margin 负值
```html
<!-- top改为-300，但是图片并没有产生新的偏移
原因：被vertical-align:baseline限死 -->
 <div class="box">
      <img src="mm1.jpg">
</div>
<style>
.box > img {
       height: 96px;
       margin-top: -200px;
}
</style>
```

#### border与透明边框技巧

- 需求：一个宽度不固定的元素，要在距离右边缘50px的位置设置一个背景图
```css
.box {
      border-right: 50px solid transparent;
      background-position: 100% 50%;
}
```

- 增加点击区域
透明border与padding相比的优势：雪碧图只需要留下足够的间距即可

- 绘制三角形

## ch5

- 字母x的下边缘就是我们的基线
- vertical-align:middle  这里的middle 指的是基线往上1/2 x-height（小写字母x的）高度，根据字体的不同，他并不是绝对的垂直居中对齐

#### css单位ex
- 指的是小写字母 x 的高度
- 图标和文字天然的垂直居中，且不受字体和字号的影响
https://demo.cssworld.cn/5/1-1.php
```css
.icon-arrow {
      display: inline-block;
      width: 20px;
      height: 1ex;
      background: url(arrow.png) no-repeat center;
}
```

#### line-height
- 非替换元素的纯内联元素的**可视**高度完全由line-height决定
- 利用line-height实现的垂直居中（单行多行都行）
```html
<style>
.box {
       line-height: 120px;
       background-color: #f0f3f9;
}
.content {
       display: inline-block;
       line-height: 20px;
       margin: 0 20px;
       vertical-align: middle;
}
</style>
<div class="box">
  <div class="content">基于行高实现的...</div>
</div>
```
- line-height   
计算目标:font-size
1.5/150%/1.5em 区别：在发生继承的情况下，1.5继承的是属性值，而150%和1.5em则继承到了父元素的计算结果值

#### vertiacl-align
- vertiacl-align只针对内联元素起作用
- 关于box的高度为啥高于32px，见书p132页
```html
<style>
.box { line-height: 32px; }
.box > span { font-size: 24px; }
</style>
<div class="box">
    <span>文字</span> 
</div>
```
- 一个 inline-block 元素，如果里面没有内联元素，或者 overflow 不是 visible， 则该元素的基线就是其 margin 底边缘;否则其基线就是元素里面最后一行内联元素的基线。
```html
<!-- 神奇的demo -->
<style>
.dib-baseline {
  display: inline-block;
  width: 150px; height: 150px;
  border: 1px solid #cad5eb;
  background-color: #f0f3f9;
}
</style>
<span class="dib-baseline"></span>
<span class="dib-baseline">x-baseline</span>
```
所以这里又有一个图标和文字对齐的方案（可自由调整文字大小）
```html
<style>
.icon {
      display: inline-block;
      width: 20px; height: 20px;
      background: url(sprite.png) no-repeat;
      white-space: nowrap;
      letter-spacing: -1em;
      text-indent: -999em;
}
.icon:before {
      content: '\3000';
}
.icon-xxx {
      background-position: 0 -20px;
}
</style>
<p><i class="icon icon-delete"></i>删除</p>
```

同样也可以实现纯css的水平垂直居中,但是感觉还是使用position:fix和margin:auto的方式居中比较好理解，所以就不放出了

## ch6

flex大行其道的现在，这节可选看

常见情况：float之后 高度塌陷
#### float特性
- 包裹性;
- 块状化并格式化上下文; 
- 破坏文档流;
- 没有任何 margin 合并;

简单的块元素右对齐可以使用margin-left:auto来实现，没必要使用float

#### clear注意点
clear定义：元素盒子的边不能和前面的浮动元素相邻。
```css
/*
假设容器宽度足够宽，有 10 个<li>元素，设置了如下 CSS 代码
依然只有两行,根据定义，clear只能对单边其效果，所以 都用both吧
*/
li {
      width: 20px; height: 20px;
      margin: 5px;
      float: left;
}
li:nth-of-type(3) {
      clear: both;
}
```

#### BFC
块级格式化上下文
具有 BFC 特性的元素的子元素不会受外部元素影响，也不会影响外 部元素

##### 触发条件
- <html>根元素;
- float 的值不为 none;
- overflow 的值为 auto、scroll 或 hidden;
- display 的值为 table-cell、table-caption 和 inline-block 中的任何一个;
- position 的值不为 relative 和 static。

##### 常用方案

```css
.lbf-content { overflow: hidden; }
.lbf-content {
display: table-cell; width: 9999px; 
}
```

#### 让页面滚动条不发生晃动的小技巧 
```css
html {
  overflow-y: scroll;
}
:root {
  overflow-y: auto;
  overflow-x: hidden;
}
:root body {
  position: absolute;
}
body {
  width: 100vw;
  overflow: hidden;
}
```

#### 锚点实现切换选项卡效果
原理：overflow:hidden 元素依然可以滚动

demo:http://demo.cssworld.cn/6/4-3.php

缺点：
- 容器高度需要固定
- 由内而外的锚点定位会触发窗体的重定位

第二个缺点 通过label触发input的focus来解决，配合:checked伪类可以完成样式的变化

#### 具有相对特性的无依赖absolute绝对定位

一个绝对定位元素，没有任何 left/top/right/bottom 属性设置，并且其祖先元素全部都是非定位元素，其位置在 哪里?
实际上，还是当前位置，不是在浏览器左上方。
本质上是相对定位，但是不占据css流的尺寸空间

用途：导航文字右上方图标示意
- 因为是紧跟在文字后面，所以当文字字数修改了也不需要修改top/right值
- 当不需要了 直接删除该元素和样式即可
```css
.icon-hot {
      position: absolute;
      margin: -6px 0 0 2px;
      width: 28px; height: 11px;
      background: url(hot.gif);
}
```

##### 规则
- 从左往右依次寻找本地是否有对应字体
- 不区分大小写
- 如果字体名包含空格，需要使用引号包起来
```css
body {
      font-family: 'PingFang SC', 'Microsoft Yahei',simsun;
}
```

##### 分类
```css
body{
    font-family: serif;  /* 衬线字体 */
    font-family: sans-serif;  /* 无衬线字体 */
    font-family: monospace;  /* 等宽字体 */
    font-family: cursive;  /* 手写字体 */
    font-family: fantasy;  /* 奇幻字体 */
    font-family: system-ui; /* 系统ui字体 */
} 
```

- 衬线字体：笔画开始、结束的地方有额外装饰且笔画粗线会有所不同，常用的衬线字体：宋体，times new roman
- 无衬线字体：没有额外的装饰，笔画粗细相近，常用无衬线字体：雅黑，arial
- 等宽字体：每个字符在同等font-size下占据的宽度一样，常用等宽字体：Consolas, Monaco, monospace;

#### ch
和em,rem,ex一样，1ch表示一个0字符的宽度，配合等宽字体，宽度11ch，则代表11位数字的宽度
需求：代码一个个出现的动效可以通过overflow+animation的方式纯css实现

#### font-weight
如果使用数值，只能是100-900的整百数，400和700为临界点
400 = normal
700 = bold
bolder 和 lighter 根据父元素进行临界点进位
非临界点感觉没有变化 是因为我们的系统里缺乏对应的字体（该字体家族全部的字重字体）

#### font-face

如果无需兼容ie8，则可以舍弃eot格式
如果无需兼容安卓4.3以及之前的版本，则可以舍弃ttf格式
现代的话 直接使用woff2和woff就行了

由于 IE6~IE8 不认识功能符，于是下面一个 src 被完美避开了
要兼容性的话可以使用如下代码
```css
@font-face {
      font-family: ICON;
      src: url('icon.eot');
      src: local('☺'),
          url('icon.woff2') format("woff2"),
          url('icon.woff') format("woff"),
          url('icon.ttf');
}
```

TL;DR
```css
@font-face {
      font-family: ICON;
      src: url('icon.eot') format('eot');
      src: url('icon.eot?#iefix') format('embedded-opentype'),
          url('icon.woff2') format("woff2")
          url('icon.woff') format("woff"),
          url('icon.ttf') format("typetrue");
      font-weight: normal;
      font-style: normal;
}
```
- eot：IE浏览器私有，所有IE都支持
- woff：专门为web开发设计的字体，安卓4.4开始全面支持
- woff2：woff优化版，chrome和firefox支持较好
- ttf：系统安装字体，尺寸大，但是兼容性较好
- IE9 **之前的**版本解析有一个严重的问题，当 src 属性包含多个 url()时，会把长长的字符当作一个地址解析而返回 404 错误。因此把 eot 格式放在第一位，然后在字体文件 url 地址后加上问号，这样 IE9 之前的版本会把问号之后 的内容当作 url 的参数
- 第一个的src属性是为了兼容（兼容模式下的IE7/IE8），此模式下不认识问号
- format可以让浏览器提前知道是否需要下载该格式的字体，属于优化，建议保留

#### font-style/font-weight在font-face中的应用
制定一个字体，名叫'I'，当文字样式正常的时候，字体表现使用“方 正姚体”;当文字设置了 font-style:italic 的时候，字体表现为“方正舒体”。
font-weight同理，因为值比较多，所以比style适用性更强
```css
@font-face {
      font-family: 'I';
      font-style: normal;
      src: local('FZYaoti');
}
@font-face {
      font-family: 'I';
      font-style: italic;
      src: local('FZShuTi');
}
```

#### unicode-range
指定字符设置指定的字体
相关字符集 参考https://www.zhangxinxu.com/wordpress/2016/11/css-unicode-range-character-font-face/
注：ie8不支持
```css
@font-face {
  font-family: BASE;
  src: local("Microsoft Yahei");
}
@font-face {
  font-family: quote;
  src: local('SimSun');    
  unicode-range: U+201c, U+201d;
}
.font {
    font-family: quote, BASE;
}
```

#### text-justify
在默认设置下，text-align:justify 要想有两端对齐的效果，需要满足两点:一是有分隔点，如空格;二是要超过一行，此时非最后一行内容会两端对齐

兼容方案,通过伪元素给后面加一行
```css
.justify {
      text-align: justify;
      font-size: .1px;  /* IE */
      font-size: -webkit-calc(0px + 0px);  /*chrome最小size为12的重置 */
}
.justify:after {
      content: "";
      display: inline-table;
      width: 100%;
      vertical-align: bottom;
}
.justify li {
      display: inline-block;
      font-size: 14px;
}
```

#### text-transform
输入内容强制大写或者小写
使用场景：
- 身份证输入最后一位的X
- 验证码输入
```css
input {
      text-transform: uppercase;
}
```

#### :first-letter伪元素
场景：金额的单位样式
```css
.price:first-letter {
      margin-right: 5px;
      font-size: xx-large;
      vertical-align: -2px;
}
/* <p>¥399</p> */
```

#### visibility:hidden和display:none

- 父元素设置 visibility:hidden，子元素也 会看不见，究其原因是继承性，子元素继承了 visibility:hidden，但是，如果子元素设置 了 visibility:visible，则子元素又会显示出来。
- CSS3 transition支持的CSS属性中有visibility

所以可以直接通过css解决hover误触问题
demo: http://demo.cssworld.cn/10/2-3.php 
```html
<style>
.list {
  position: absolute;
  visibility: hidden;
}
td:hover .list {
  visibility: visible;
  transition: visibility 0s .2s;
}
</style>
<td>
  <a href>操作▾</a> 
  <div class="list">
    <a href>编辑</a>
    <a href>删除</a> 
  </div>
</td>
```
